const GET_ALL_CRYPTOS = 'GET_ALL_CRYPTOS'
const GET_BY_ID = 'GET_BY_ID'
const GET_BY_NAME = 'GET_BY_NAME'
const CURRENT_PAGE = 'CURRENT_PAGE'
const SPECIFIC_PAGE = 'SPECIFIC_PAGE'

export {
  GET_ALL_CRYPTOS,
  GET_BY_ID,
  GET_BY_NAME,
  CURRENT_PAGE,
  SPECIFIC_PAGE,
}